---
title: "DensityReport"
output:
  html_document:
    df_print: paged
---

```{r Preparation, echo=FALSE,warning=FALSE}
library(ggplot2)
library(ggpubr)

createBoxplot <- function(list, AAname, type="UR"){
    firstORF <- data.frame(orfNum = "First ORF", OrfDensity = list$`First ORF`)
    secondORF <- data.frame(orfNum = "Second ORF", OrfDensity = list$`Second ORF`)
    thirdORF <- data.frame(orfNum = "Third ORF", OrfDensity = list$`Third ORF`)
    coding <- data.frame(orfNum = "Coding transcripts", OrfDensity = list$`Coding transcripts`)
    if(length(list)==4){
      plot.data <- rbind(firstORF,secondORF,thirdORF,coding)
  
      my_comparisons <- list( c("First ORF", "Second ORF"), c("First ORF", "Third ORF"), c ("First ORF", "Coding transcripts"), c("Second ORF", "Third ORF"), c("Second ORF", "Coding transcripts"), c("Third ORF", "Coding transcripts"))
    }
    if(length(list)==5){
      fourthORF <- data.frame(orfNum = "Fourth ORF", OrfDensity = list$`Fourth ORF`)
      
      plot.data <- rbind(firstORF,secondORF,thirdORF,fourthORF,coding)
      
      my_comparisons <- list( c("First ORF", "Second ORF"), c("First ORF", "Third ORF"),c("First ORF", "Fourth ORF"), c ("First ORF", "Coding transcripts"), c("Second ORF", "Third ORF"),c("Second ORF", "Fourth ORF"), c("Second ORF", "Coding transcripts"), c("Third ORF", "Fourth ORF"), c("Third ORF", "Coding transcripts"),c("Fourth ORF", "Coding transcripts"))
    }
    if(length(list)==6){
      fourthORF <- data.frame(orfNum = "Fourth ORF", OrfDensity = list$`Fourth ORF`)
      fifthORF <- data.frame(orfNum = "Fifth ORF", OrfDensity = list$`Fifth ORF`)
      
      plot.data <- rbind(firstORF,secondORF,thirdORF,fourthORF,fifthORF,coding)
      
      my_comparisons <- list( c("First ORF", "Second ORF"), c("First ORF", "Third ORF"),c("First ORF", "Fourth ORF"),c("First ORF", "Fifth ORF"), c ("First ORF", "Coding transcripts"), c("Second ORF", "Third ORF"),c("Second ORF", "Fourth ORF"),c("Second ORF", "Fifth ORF"), c("Second ORF", "Coding transcripts"), c("Third ORF", "Fourth ORF"),c("Third ORF", "Fifth ORF"), c("Third ORF", "Coding transcripts"),c("Fourth ORF", "Fifth ORF"),c("Fourth ORF", "Coding transcripts"),c("Fifth ORF", "Coding transcripts"))
    }
  
  if(type=="c"){
    print(ggplot(plot.data, aes(x=orfNum, y=OrfDensity, fill=orfNum)) + geom_boxplot() +  xlab("Set") + ylab (paste0(AAname," density\n"))+ labs(fill = "Set") + theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())+geom_hline(yintercept = 0) + geom_vline(xintercept = 0) + expand_limits(x = 0, y = 0) + ggtitle(paste0(AAname," density for complete ORFs and protein coding transcripts"))+stat_compare_means(comparisons = my_comparisons) + stat_compare_means(label.y = -0.05,label.x = 1))
  }
  else{
    print(ggplot(plot.data, aes(x=orfNum, y=OrfDensity, fill=orfNum)) + geom_boxplot() +  xlab("Set") + ylab (paste0(AAname," density\n"))+ labs(fill = "Set") + theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())+geom_hline(yintercept = 0) + geom_vline(xintercept = 0) + expand_limits(x = 0, y = 0) + ggtitle(paste0(AAname," density for unique regions and protein coding transcripts"))+stat_compare_means(comparisons = my_comparisons) + stat_compare_means(label.y = -0.05,label.x = 1))
  }
}

names=c("Alanine","Arginine","Asparagine","Aspartic acid", "Cysteine", "Glutamine", "Glycine", "Glutamic acid", "Histidine", "Isoleucine", "Leucine", "Lysine","Methionine","Phenylalanine","Proline","Serine","Threonine","Tryptophan","Tyrosine","Valine")
```

# Human

### NMD

#### Complete ORFs

```{r HumanNMD, echo=FALSE, out.width="50%", warning=FALSE}

NMDDenseFirstOrf=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/HIWI/Human/NMD/All_AA_density_first_ORF.tsv',
  sep = '\t', header = TRUE)
NMDDenseSecondOrf=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/HIWI/Human/NMD/All_AA_density_second_ORF.tsv',
  sep = '\t', header = TRUE)
NMDDenseThirdOrf=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/HIWI/Human/NMD/All_AA_density_third_ORF.tsv',
  sep = '\t', header = TRUE)
NMDDenseFourthOrf=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/HIWI/Human/NMD/All_AA_density_fourth_ORF.tsv',
  sep = '\t', header = TRUE)

CodingDense=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/PipeTest/Pipeline/Input/human/All_AA_density.tsv',
  sep = '\t', header = TRUE)

NMDdensitiesOrf=list()
for(i in 1:20){
  NMDdensitiesOrf=c(NMDdensitiesOrf,list(c("First ORF" = list(NMDDenseFirstOrf[,i+1]),"Second ORF" = list(NMDDenseSecondOrf[,i+1]),"Third ORF" = list(NMDDenseThirdOrf[,i+1]),"Fourth ORF" = list(NMDDenseFourthOrf[,i+1]),"Coding transcripts" = list(CodingDense[,i+1]))))
}

for(i in 1:20){
  createBoxplot(NMDdensitiesOrf[[i]],names[[i]],"c")
}

```

#### Unique regions

```{r HumanNMDunique, echo=FALSE, out.width="50%", warning=FALSE}

NMDDenseFirst=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/HIWI/Human/NMD/All_AA_density_first_ORF_UR.tsv',
  sep = '\t', header = TRUE)
NMDDenseSecond=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/HIWI/Human/NMD/All_AA_density_second_ORF_UR.tsv',
  sep = '\t', header = TRUE)
NMDDenseThird=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/HIWI/Human/NMD/All_AA_density_third_ORF_UR.tsv',
  sep = '\t', header = TRUE)

names=c("Alanine","Arginine","Asparagine","Aspartic acid", "Cysteine", "Glutamine", "Glycine", "Glutamic acid", "Histidine", "Isoleucine", "Leucine", "Lysine","Methionine","Phenylalanine","Proline","Serine","Threonine","Tryptophan","Tyrosine","Valine")
NMDdensities=list()
for(i in 1:20){
  NMDdensities=c(NMDdensities,list(c("First ORF" = list(NMDDenseFirst[,i+1]),"Second ORF" = list(NMDDenseSecond[,i+1]),"Third ORF" = list(NMDDenseThird[,i+1]),"Coding transcripts" = list(CodingDense[,i+1]))))
}

for(i in 1:20){
  createBoxplot(NMDdensities[[i]],names[[i]])
}

```


### RI

#### Complete ORFs

```{r HumanRI, echo=FALSE, fig.show="hold", out.width="50%", warning=FALSE}

RIDenseFirstOrf=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/HIWI/Human/RI/All_AA_density_first_ORF.tsv',
  sep = '\t', header = TRUE)
RIDenseSecondOrf=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/HIWI/Human/RI/All_AA_density_second_ORF.tsv',
  sep = '\t', header = TRUE)
RIDenseThirdOrf=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/HIWI/Human/RI/All_AA_density_third_ORF.tsv',
  sep = '\t', header = TRUE)
RIDenseFourthOrf=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/HIWI/Human/RI/All_AA_density_fourth_ORF.tsv',
  sep = '\t', header = TRUE)
RIDenseFifthOrf=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/HIWI/Human/RI/All_AA_density_fifth_ORF.tsv',
  sep = '\t', header = TRUE)

RIdensitiesOrf=list()
for(i in 1:20){
  RIdensitiesOrf=c(RIdensitiesOrf,list(c("First ORF" = list(RIDenseFirstOrf[,i+1]),"Second ORF" = list(RIDenseSecondOrf[,i+1]),"Third ORF" = list(RIDenseThirdOrf[,i+1]),"Fourth ORF" = list(RIDenseFourthOrf[,i+1]),"Fifth ORF" = list(RIDenseFifthOrf[,i+1]),"Coding transcripts" = list(CodingDense[,i+1]))))
}

for(i in 1:20){
  createBoxplot(RIdensitiesOrf[[i]],names[[i]],"c")
}

```

#### Unique regions

```{r HumanRIunique, echo=FALSE, fig.show="hold", out.width="50%", warning=FALSE}

RIDenseFirst=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/HIWI/Human/RI/All_AA_density_first_ORF_UR.tsv',
  sep = '\t', header = TRUE)
RIDenseSecond=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/HIWI/Human/RI/All_AA_density_second_ORF_UR.tsv',
  sep = '\t', header = TRUE)
RIDenseThird=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/HIWI/Human/RI/All_AA_density_third_ORF_UR.tsv',
  sep = '\t', header = TRUE)
RIDenseFourth=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/HIWI/Human/RI/All_AA_density_fourth_ORF_UR.tsv',
  sep = '\t', header = TRUE)
RIDenseFifth=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/HIWI/Human/RI/All_AA_density_fifth_ORF_UR.tsv',
  sep = '\t', header = TRUE)

RIdensities=list()
for(i in 1:20){
  RIdensities=c(RIdensities,list(c("First ORF" = list(RIDenseFirst[,i+1]),"Second ORF" = list(RIDenseSecond[,i+1]),"Third ORF" = list(RIDenseThird[,i+1]),"Fourth ORF" = list(RIDenseFourth[,i+1]),"Fifth ORF" = list(RIDenseFifth[,i+1]),"Coding transcripts" = list(CodingDense[,i+1]))))
}

for(i in 1:20){
  createBoxplot(RIdensities[[i]],names[[i]])
}

```


# Mouse

### NMD

#### Complete ORFs

```{r MouseNMD, echo=FALSE, out.width="50%", warning=FALSE}

NMDMouseDenseFirstOrf=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/HIWI/Mouse/NMD/All_AA_density_first_ORF.tsv',
  sep = '\t', header = TRUE)
NMDMouseDenseSecondOrf=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/HIWI/Mouse/NMD/All_AA_density_second_ORF.tsv',
  sep = '\t', header = TRUE)
NMDMouseDenseThirdOrf=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/HIWI/Mouse/NMD/All_AA_density_third_ORF.tsv',
  sep = '\t', header = TRUE)
NMDMouseDenseFourthOrf=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/HIWI/Mouse/NMD/All_AA_density_third_ORF.tsv',
  sep = '\t', header = TRUE)

CodingMouseDense=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/Raw-Data/Mouse/All_AA_density.tsv',
  sep = '\t', header = TRUE)

NMDdensitiesMouseOrf=list()
for(i in 1:20){
  NMDdensitiesMouseOrf=c(NMDdensitiesMouseOrf,list(c("First ORF" = list(NMDMouseDenseFirstOrf[,i+1]),"Second ORF" = list(NMDMouseDenseSecondOrf[,i+1]),"Third ORF" = list(NMDMouseDenseThirdOrf[,i+1]),"Fourth ORF" = list(NMDMouseDenseFourthOrf[,i+1]),"Coding transcripts" = list(CodingMouseDense[,i+1]))))
}

for(i in 1:20){
  createBoxplot(NMDdensitiesMouseOrf[[i]],names[[i]],"c")
}
```

#### Unique regions

```{r MouseNMDunique, echo=FALSE, out.width="50%", warning=FALSE}

NMDMouseDenseFirst=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/HIWI/Mouse/NMD/All_AA_density_first_ORF_UR.tsv',
  sep = '\t', header = TRUE)
NMDMouseDenseSecond=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/HIWI/Mouse/NMD/All_AA_density_second_ORF_UR.tsv',
  sep = '\t', header = TRUE)
NMDMouseDenseThird=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/HIWI/Mouse/NMD/All_AA_density_third_ORF_UR.tsv',
  sep = '\t', header = TRUE)

CodingMouseDense=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/Raw-Data/Mouse/All_AA_density.tsv',
  sep = '\t', header = TRUE)

NMDdensitiesMouse=list()
for(i in 1:20){
  NMDdensitiesMouse=c(NMDdensitiesMouse,list(c("First ORF" = list(NMDMouseDenseFirst[,i+1]),"Second ORF" = list(NMDMouseDenseSecond[,i+1]),"Third ORF" = list(NMDMouseDenseThird[,i+1]),"Coding transcripts" = list(CodingMouseDense[,i+1]))))
}

for(i in 1:20){
  createBoxplot(NMDdensitiesMouse[[i]],names[[i]])
}
```


### RI

#### Complete ORFs

```{r MouseRI, echo=FALSE, fig.show="hold", out.width="50%", warning=FALSE}

RIMouseDenseFirstOrf=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/HIWI/Mouse/RI/All_AA_density_first_ORF.tsv',
  sep = '\t', header = TRUE)
RIMouseDenseSecondOrf=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/HIWI/Mouse/RI/All_AA_density_second_ORF.tsv',
  sep = '\t', header = TRUE)
RIMouseDenseThirdOrf=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/HIWI/Mouse/RI/All_AA_density_third_ORF.tsv',
  sep = '\t', header = TRUE)
RIMouseDenseFourthOrf=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/HIWI/Mouse/RI/All_AA_density_fourth_ORF.tsv',
  sep = '\t', header = TRUE)

RIdensitiesMouseOrf=list()
for(i in 1:20){
  RIdensitiesMouseOrf=c(RIdensitiesMouseOrf,list(c("First ORF" = list(RIMouseDenseFirstOrf[,i+1]),"Second ORF" = list(RIMouseDenseSecondOrf[,i+1]),"Third ORF" = list(RIMouseDenseThirdOrf[,i+1]),"Fourth ORF" = list(RIMouseDenseFourthOrf[,i+1]),"Coding transcripts" = list(CodingMouseDense[,i+1]))))
}

for(i in 1:20){
  createBoxplot(RIdensitiesMouseOrf[[i]],names[[i]],"c")
}
```

#### Unique regions

```{r MouseRIunique, echo=FALSE, fig.show="hold", out.width="50%", warning=FALSE}

RIMouseDenseFirst=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/HIWI/Mouse/RI/All_AA_density_first_ORF_UR.tsv',
  sep = '\t', header = TRUE)
RIMouseDenseSecond=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/HIWI/Mouse/RI/All_AA_density_second_ORF_UR.tsv',
  sep = '\t', header = TRUE)
RIMouseDenseThird=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/HIWI/Mouse/RI/All_AA_density_third_ORF_UR.tsv',
  sep = '\t', header = TRUE)
RIMouseDenseFourth=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/HIWI/Mouse/RI/All_AA_density_fourth_ORF_UR.tsv',
  sep = '\t', header = TRUE)

RIdensitiesMouse=list()
for(i in 1:20){
  RIdensitiesMouse=c(RIdensitiesMouse,list(c("First ORF" = list(RIMouseDenseFirst[,i+1]),"Second ORF" = list(RIMouseDenseSecond[,i+1]),"Third ORF" = list(RIMouseDenseThird[,i+1]),"Fourth ORF" = list(RIMouseDenseFourth[,i+1]),"Coding transcripts" = list(CodingMouseDense[,i+1]))))
}

for(i in 1:20){
  createBoxplot(RIdensitiesMouse[[i]],names[[i]])
}
```
