---
title: "TranscriptStatistics"
output:
  #pdf_document: default
  html_document: default
---

```{r setup, echo=FALSE,warning=FALSE}
library(ggplot2)
library(ggpubr)
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, fig.height = 7, fig.width = 10)

createBoxplot <- function(list, AAname){
    splitTrans <- data.frame(TranscriptType = "split-ORF encoding transcripts", TransDensity = list$`split-ORF encoding transcripts`)
    nonsplitTrans <- data.frame(TranscriptType = "remaining NMD transcripts", TransDensity = list$`remaining NMD transcripts`)
    coding <- data.frame(TranscriptType = "Coding transcripts", TransDensity = list$`Coding transcripts`)
    
    plot.data <- rbind(splitTrans,nonsplitTrans,coding)
    
    my_comparisons <- list( c(1, 2), c(1, 3), c (2, 3))
    
    print(ggplot(plot.data, aes(x=TranscriptType, y=TransDensity, fill=TranscriptType)) + geom_boxplot() +  xlab("TranscriptType") + ylab (paste0(AAname," density\n"))+ labs(fill = "TranscriptType") + theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())+geom_hline(yintercept = 0) + geom_vline(xintercept = 0) + expand_limits(x = 0, y = 0) + ggtitle(paste0(AAname," density for NMD and protein coding transcripts"))+ stat_summary(fun=mean, colour="darkred", geom="text", show.legend = FALSE, vjust=-1, aes( label=round(..y.., digits=4)))+ stat_summary(fun=mean, colour="darkred", geom="point", shape=18, size=2,show.legend = FALSE)+stat_compare_means(comparisons = my_comparisons) + stat_compare_means(label.y = -0.05,label.x = 1))
  
}

names=c("Alanine","Arginine","Asparagine","Aspartic acid", "Cysteine", "Glutamine", "Glycine", "Glutamic acid", "Histidine", "Isoleucine", "Leucine", "Lysine","Methionine","Phenylalanine","Proline","Serine","Threonine","Tryptophan","Tyrosine","Valine")

```

# Human

```{r InputHuman, echo=FALSE}
splitTranscripts=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/PipeTest/Pipeline/Output/run_25.11.2021-15.07.16_NMD/split-ORF_Transcripts_length.tsv',
  sep = '\t', header = FALSE)
splitlengths=splitTranscripts[,2]

nonSplitTranscripts=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/PipeTest/Pipeline/Output/run_25.11.2021-15.07.16_NMD/non-split-ORF_Transcripts_length.tsv',
  sep = '\t', header = FALSE)
nonsplitlengths=nonSplitTranscripts[,2]


splitTranscriptsDense=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/PipeTest/Pipeline/Output/run_25.11.2021-15.07.16_NMD/NMD_split-ORF_Transcripts_AA_density.tsv',
  sep = '\t', header = TRUE)

nonSplitTranscriptsDense=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/PipeTest/Pipeline/Output/run_25.11.2021-15.07.16_NMD/NMD_non-split-ORF_Transcripts_AA_density.tsv',
  sep = '\t', header = TRUE)


RIsplitTranscripts=read.table(
  file = "/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/PipeTest/Pipeline/Output/run_25.11.2021-17.34.47_RI/split-ORF_Transcripts_length.tsv",
  sep = '\t', header = FALSE)
RIsplitlengths=RIsplitTranscripts[,2]

RINonsplitTranscripts=read.table(
  file = "/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/PipeTest/Pipeline/Output/run_25.11.2021-17.34.47_RI/non-split-ORF_Transcripts_length.tsv",
  sep = '\t', header = FALSE)
RINonsplitlengths=RINonsplitTranscripts[,2]


codingTranscripts=read.table(
  file = "/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/PipeTest/Pipeline/Input/human/Protein_coding_peptide_length.tsv",
  sep = '\t', header = FALSE)
codinglengths=codingTranscripts[,2]


CodingDense=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/PipeTest/Pipeline/Input/human/All_AA_density.tsv',
  sep = '\t', header = TRUE)

NMDdensities=list()
for(i in 1:20){
  NMDdensities=c(NMDdensities,list(c("split-ORF encoding transcripts" = list(splitTranscriptsDense[,i+1]),"remaining NMD transcripts" = list(nonSplitTranscriptsDense[,i+1]),"Coding transcripts" = list(CodingDense[,i+1]))))
}


splitORFNMDtranscripts <- data.frame(TranscriptType = "split-ORF NMD transcripts", TranscriptLength = splitlengths)
nonsplitORFNMDtranscripts <- data.frame(TranscriptType = "non split-ORF NMD transcripts", TranscriptLength = nonsplitlengths)
splitORFIRtranscripts <- data.frame(TranscriptType = "split-ORF IR transcripts", TranscriptLength = RIsplitlengths)
nonsplitORFIRtranscripts <- data.frame(TranscriptType = "non split-ORF IR transcripts", TranscriptLength = RINonsplitlengths)
codingtranscripts <- data.frame(TranscriptType = "coding transcripts", TranscriptLength = codinglengths)


```

## Length Distribution of split-ORF encoding NMD transcripts, split-ORF encoding RI transcripts and coding transcripts


```{r OutputHuman}

plot.data <- rbind(splitORFNMDtranscripts, nonsplitORFNMDtranscripts, splitORFIRtranscripts, nonsplitORFIRtranscripts, codingtranscripts)

my_comparisons <- list( c("split-ORF NMD transcripts", "non split-ORF NMD transcripts"), c("split-ORF NMD transcripts", "split-ORF IR transcripts"), c ("split-ORF NMD transcripts", "non split-ORF IR transcripts"), c("split-ORF NMD transcripts", "coding transcripts"), c("non split-ORF NMD transcripts", "split-ORF IR transcripts"),c("non split-ORF NMD transcripts", "non split-ORF IR transcripts"), c("non split-ORF NMD transcripts", "coding transcripts"), c ("split-ORF IR transcripts", "non split-ORF IR transcripts"), c("split-ORF IR transcripts", "coding transcripts"), c("non split-ORF IR transcripts", "coding transcripts"))
ggplot(plot.data, aes(x=TranscriptType, y=TranscriptLength, fill=TranscriptType)) + geom_boxplot() + scale_y_continuous(trans='log10',breaks=c(0,1,10,100,1000,10000,100000,1000000)) + xlab("Transcript Type") + ylab ("Intron length\n")+ labs(fill = "Transcript type") + theme(axis.text.x = element_blank(), axis.ticks.x = element_blank()) + geom_hline(yintercept = 0) + geom_vline(xintercept = 0) + expand_limits(x = 0, y = 0)+stat_compare_means(comparisons = my_comparisons) + stat_compare_means(label.y = 1,label.x = 1)

```

## Aminoacid density for NMD transcripts

```{r HumanDensity, out.width="50%"}
for(i in 1:20){
  createBoxplot(NMDdensities[[i]],names[[i]])
}
```

# Mouse

```{r InputMouse, echo=FALSE}
splitTranscriptsMouse=read.table(
  file = "/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/PipeTest/Pipeline/Output/run_25.11.2021-19.10.55_NMD_Mouse/split-ORF_Transcripts_length.tsv",
  sep = '\t', header = FALSE)
splitlengthsMouse=splitTranscriptsMouse[,2]

NonsplitTranscriptsMouse=read.table(
  file = "/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/PipeTest/Pipeline/Output/run_25.11.2021-19.10.55_NMD_Mouse/non-split-ORF_Transcripts_length.tsv",
  sep = '\t', header = FALSE)
NonsplitlengthsMouse=NonsplitTranscriptsMouse[,2]


splitTranscriptsDenseMouse=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/PipeTest/Pipeline/Output/run_25.11.2021-19.10.55_NMD_Mouse/NMD_split-ORF_Transcripts_AA_density.tsv',
  sep = '\t', header = TRUE)

nonSplitTranscriptsDenseMouse=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/PipeTest/Pipeline/Output/run_25.11.2021-19.10.55_NMD_Mouse/NMD_non-split-ORF_Transcripts_AA_density.tsv',
  sep = '\t', header = TRUE)


RIsplitTranscriptsMouse=read.table(
  file = "/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/PipeTest/Pipeline/Output/run_25.11.2021-19.56.04_RI_Mouse/split-ORF_Transcripts_length.tsv",
  sep = '\t', header = FALSE)
RIsplitlengthsMouse=RIsplitTranscriptsMouse[,2]

RINonsplitTranscriptsMouse=read.table(
  file = "/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/PipeTest/Pipeline/Output/run_25.11.2021-19.56.04_RI_Mouse/non-split-ORF_Transcripts_length.tsv",
  sep = '\t', header = FALSE)
RINonsplitlengthsMouse=RINonsplitTranscriptsMouse[,2]


codingTranscriptsMouse=read.table(
  file = "/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/PipeTest/Pipeline/shiny/splitORFdatabase/data/Protein_coding_DNA_mouse_length.tsv",
  sep = '\t', header = FALSE)
codinglengthsMouse=codingTranscriptsMouse[,2]


CodingDenseMouse=read.table(
  file = '/mnt/g/Justin_Backup_29.04.2020/Justin/Uni-Frankfurt/FP+Masterarbeit/Raw-Data/Mouse/All_AA_density.tsv',
  sep = '\t', header = TRUE)


splitORFNMDtranscriptsMouse <- data.frame(TranscriptType = "split-ORF NMD transcripts", TranscriptLength = splitlengthsMouse)
nonsplitORFNMDtranscriptsMouse <- data.frame(TranscriptType = "non split-ORF NMD transcripts", TranscriptLength = NonsplitlengthsMouse)
splitORFIRtranscriptsMouse <- data.frame(TranscriptType = "split-ORF IR transcripts", TranscriptLength = RIsplitlengthsMouse)
nonsplitORFIRtranscriptsMouse <- data.frame(TranscriptType = "non split-ORF IR transcripts", TranscriptLength = RINonsplitlengthsMouse)
codingtranscriptsMouse <- data.frame(TranscriptType = "coding transcripts", TranscriptLength = codinglengthsMouse)

NMDdensitiesMouse=list()
for(i in 1:20){
  NMDdensitiesMouse=c(NMDdensitiesMouse,list(c("split-ORF encoding transcripts" = list(splitTranscriptsDenseMouse[,i+1]),"remaining NMD transcripts" = list(nonSplitTranscriptsDenseMouse[,i+1]),"Coding transcripts" = list(CodingDenseMouse[,i+1]))))
}


```

## Length Distribution of split-ORF encoding NMD transcripts, split-ORF encoding RI transcripts and coding transcripts

```{r OutputMouse, echo=FALSE}
plot.dataMouse <- rbind(splitORFNMDtranscriptsMouse, nonsplitORFNMDtranscriptsMouse, splitORFIRtranscriptsMouse, nonsplitORFIRtranscriptsMouse, codingtranscriptsMouse)

my_comparisonsMouse <- list( c("split-ORF NMD transcripts", "non split-ORF NMD transcripts"), c("split-ORF NMD transcripts", "split-ORF IR transcripts"), c ("split-ORF NMD transcripts", "non split-ORF IR transcripts"), c("split-ORF NMD transcripts", "coding transcripts"), c("non split-ORF NMD transcripts", "split-ORF IR transcripts"),c("non split-ORF NMD transcripts", "non split-ORF IR transcripts"), c("non split-ORF NMD transcripts", "coding transcripts"), c ("split-ORF IR transcripts", "non split-ORF IR transcripts"), c("split-ORF IR transcripts", "coding transcripts"), c("non split-ORF IR transcripts", "coding transcripts"))
ggplot(plot.dataMouse, aes(x=TranscriptType, y=TranscriptLength, fill=TranscriptType)) + geom_boxplot() + scale_y_continuous(trans='log10',breaks=c(0,1,10,100,1000,10000,100000,1000000)) + xlab("Transcript Type") + ylab ("Intron length\n")+ labs(fill = "Transcript type") + theme(axis.text.x = element_blank(), axis.ticks.x = element_blank()) + geom_hline(yintercept = 0) + geom_vline(xintercept = 0) + expand_limits(x = 0, y = 0)+stat_compare_means(comparisons = my_comparisonsMouse) + stat_compare_means(label.y = 1,label.x = 1)


```

## Aminoacid density for NMD transcripts

```{r MouseDensity, out.width="50%"}
for(i in 1:20){
  createBoxplot(NMDdensitiesMouse[[i]],names[[i]])
}
```



