#input files at top: check them!

# all input files must be in the folder ./input/
# use the full file name, including file ending

# input splice graph
# Should be in the input folder
# format must be .vg
graph: Genome_graph.gfa

# reference transcripts
# format can be either fasta/fastq, gzipped or not
# Should be in the input folder

transcripts: Protein_coding_transcripts.fa

# sequenced reads
# Should be in the input folder
# format can be either fasta/fastq, gzipped or not
# for more files, add them in new lines starting with "- "
# NOTE: the file names without ending must be unique! You cannot have eg. reads.fq and reads.fa
reads: UniqueProteinORFPairs_sequences.fa

# Needed for expression quantificatino
# Should be in the input folder
gtffile: Genome_annotation.gtf

# needed to convert between alignment formats
# https://github.com/vgteam/vg
vgpath: $(conda info --base)/bin/vg

#optional parameters below: default values will probably work

fusion_max_error_rate: 0.2
fusion_min_score_difference: 200

#size of the seed hits. Fewer means more accurate but slower alignments.
seedsize: 17
#max number of seeds. Fewer means faster but more inaccurate alignment
maxseeds: 20

# No need to change these

aligner_bandwidth: 35
alignment_selection: --greedy-length
alignment_E_cutoff: 1

scripts: AeronScripts
binaries: Binaries


